### ISSUE TITLE
Metadata not supported

### ISSUE THREAD

**Issue by kriomant** [leon-barrett/mtbl-rs#1]
I wanted to get number of entries in MTBL file, but `mtbl_reader_metadata` function is not wrapped.

**Comment by leon-barrett** [comment]
Sorry for the slow response--I had a baby.

Yeah, the first release of this crate only covered MTBL version 0.6, which doesn't support all the metadata in later versions. I chose that version because at the time, the 0.6 library was what was shipping with stable Ubuntu, and I figured missing features were better than people finding "it doesn't work for me".

If you'd like to make a PR, I'd love that. Otherwise, I can eventually support a more recent MTBL lib, but with the baby, it's unlikely to happen terribly soon.

**Comment by leon-barrett** [comment]
Okay, v0.2.0 supports mtbl C library 0.8.0, allowing access to reader metadata via a set of reader functions.
